### PR TITLE
Build on GHC 9.2

### LINKED ISSUE #25: Cannot build on 9.2
I understand this problem is due to https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.2#sized-wordint-use-sized-wordint-primitives, but unfortunately I don't know how to provide a PR to fix this.

```
src/Data/Bytes/Builder/Bounded.hs:233:37: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word32#’
    • In the first argument of ‘wordCommonDec#’, namely ‘w’
      In the expression: wordCommonDec# w
      In an equation for ‘word32Dec’:
          word32Dec (W32# w) = wordCommonDec# w
    |
233 | word32Dec (W32# w) = wordCommonDec# w
    |                                     ^

src/Data/Bytes/Builder/Bounded.hs:238:37: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word16#’
    • In the first argument of ‘wordCommonDec#’, namely ‘w’
      In the expression: wordCommonDec# w
      In an equation for ‘word16Dec’:
          word16Dec (W16# w) = wordCommonDec# w
    |
238 | word16Dec (W16# w) = wordCommonDec# w
    |                                     ^

src/Data/Bytes/Builder/Bounded.hs:250:13: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word8#’
    • In the first argument of ‘word8Dec#’, namely ‘w’
      In the expression: word8Dec# w
      In an equation for ‘word8Dec’: word8Dec (W8# w) = word8Dec# w
    |
250 |   word8Dec# w
    |             ^

src/Data/Bytes/Builder/Bounded.hs:270:35: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int32#’
    • In the first argument of ‘intCommonDec#’, namely ‘w’
      In the expression: intCommonDec# w
      In an equation for ‘int32Dec’: int32Dec (I32# w) = intCommonDec# w
    |
270 | int32Dec (I32# w) = intCommonDec# w
    |                                   ^

src/Data/Bytes/Builder/Bounded.hs:277:35: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int16#’
    • In the first argument of ‘intCommonDec#’, namely ‘w’
      In the expression: intCommonDec# w
      In an equation for ‘int16Dec’: int16Dec (I16# w) = intCommonDec# w
    |
277 | int16Dec (I16# w) = intCommonDec# w
    |                                   ^

src/Data/Bytes/Builder/Bounded.hs:284:33: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int8#’
    • In the first argument of ‘intCommonDec#’, namely ‘w’
      In the expression: intCommonDec# w
      In an equation for ‘int8Dec’: int8Dec (I8# w) = intCommonDec# w
    |
284 | int8Dec (I8# w) = intCommonDec# w
    |                                 ^

src/Data/Bytes/Builder/Bounded.hs:444:55: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word32#’
    • In the first argument of ‘word32PaddedUpperHex#’, namely ‘w’
      In the expression: word32PaddedUpperHex# w
      In an equation for ‘word32PaddedUpperHex’:
          word32PaddedUpperHex (W32# w) = word32PaddedUpperHex# w
    |
444 | word32PaddedUpperHex (W32# w) = word32PaddedUpperHex# w
    |                                                       ^

src/Data/Bytes/Builder/Bounded.hs:450:55: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word32#’
    • In the first argument of ‘word32PaddedLowerHex#’, namely ‘w’
      In the expression: word32PaddedLowerHex# w
      In an equation for ‘word32PaddedLowerHex’:
          word32PaddedLowerHex (W32# w) = word32PaddedLowerHex# w
    |
450 | word32PaddedLowerHex (W32# w) = word32PaddedLowerHex# w
    |                                                       ^

src/Data/Bytes/Builder/Bounded.hs:459:55: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word16#’
    • In the first argument of ‘word16PaddedUpperHex#’, namely ‘w’
      In the expression: word16PaddedUpperHex# w
      In an equation for ‘word16PaddedUpperHex’:
          word16PaddedUpperHex (W16# w) = word16PaddedUpperHex# w
    |
459 | word16PaddedUpperHex (W16# w) = word16PaddedUpperHex# w
    |                                                       ^

src/Data/Bytes/Builder/Bounded.hs:468:55: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word16#’
    • In the first argument of ‘word16PaddedLowerHex#’, namely ‘w’
      In the expression: word16PaddedLowerHex# w
      In an equation for ‘word16PaddedLowerHex’:
          word16PaddedLowerHex (W16# w) = word16PaddedLowerHex# w
    |
468 | word16PaddedLowerHex (W16# w) = word16PaddedLowerHex# w
    |                                                       ^

src/Data/Bytes/Builder/Bounded.hs:477:43: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word16#’
    • In the first argument of ‘word16LowerHex#’, namely ‘w’
      In the expression: word16LowerHex# w
      In an equation for ‘word16LowerHex’:
          word16LowerHex (W16# w) = word16LowerHex# w
    |
477 | word16LowerHex (W16# w) = word16LowerHex# w
    |                                           ^

src/Data/Bytes/Builder/Bounded.hs:486:43: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word16#’
    • In the first argument of ‘word16UpperHex#’, namely ‘w’
      In the expression: word16UpperHex# w
      In an equation for ‘word16UpperHex’:
          word16UpperHex (W16# w) = word16UpperHex# w
    |
486 | word16UpperHex (W16# w) = word16UpperHex# w
    |                                           ^

src/Data/Bytes/Builder/Bounded.hs:492:40: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word8#’
    • In the first argument of ‘word8LowerHex#’, namely ‘w’
      In the expression: word8LowerHex# w
      In an equation for ‘word8LowerHex’:
          word8LowerHex (W8# w) = word8LowerHex# w
    |
492 | word8LowerHex (W8# w) = word8LowerHex# w
    |                                        ^

src/Data/Bytes/Builder/Bounded.hs:498:52: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word8#’
    • In the first argument of ‘word8PaddedUpperHex#’, namely ‘w’
      In the expression: word8PaddedUpperHex# w
      In an equation for ‘word8PaddedUpperHex’:
          word8PaddedUpperHex (W8# w) = word8PaddedUpperHex# w
    |
498 | word8PaddedUpperHex (W8# w) = word8PaddedUpperHex# w
    |                                                    ^

src/Data/Bytes/Builder/Bounded.hs:504:52: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word8#’
    • In the first argument of ‘word8PaddedLowerHex#’, namely ‘w’
      In the expression: word8PaddedLowerHex# w
      In an equation for ‘word8PaddedLowerHex’:
          word8PaddedLowerHex (W8# w) = word8PaddedLowerHex# w
    |
504 | word8PaddedLowerHex (W8# w) = word8PaddedLowerHex# w
    |                                                    ^

src/Data/Bytes/Builder/Bounded.hs:856:39: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word32#’
    • In the first argument of ‘W#’, namely ‘w’
      In the first argument of ‘lebCommon’, namely ‘(W# w)’
      In the expression: lebCommon (W# w)
    |
856 | word32LEB128 (W32# w) = lebCommon (W# w)
    |                                       ^

src/Data/Bytes/Builder/Bounded.hs:936:36: error:
    • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
    • In the first argument of ‘W32#’, namely ‘(int2Word# i)’
      In the first argument of ‘word32BE’, namely ‘(W32# (int2Word# i))’
      In the expression: word32BE (W32# (int2Word# i))
    |
936 | int32BE (I32# i) = word32BE (W32# (int2Word# i))
    |                                    ^^^^^^^^^^^

src/Data/Bytes/Builder/Bounded.hs:936:46: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int32#’
    • In the first argument of ‘int2Word#’, namely ‘i’
      In the first argument of ‘W32#’, namely ‘(int2Word# i)’
      In the first argument of ‘word32BE’, namely ‘(W32# (int2Word# i))’
    |
936 | int32BE (I32# i) = word32BE (W32# (int2Word# i))
    |                                              ^

src/Data/Bytes/Builder/Bounded.hs:939:36: error:
    • Couldn't match expected type ‘Word16#’ with actual type ‘Word#’
    • In the first argument of ‘W16#’, namely ‘(int2Word# i)’
      In the first argument of ‘word16BE’, namely ‘(W16# (int2Word# i))’
      In the expression: word16BE (W16# (int2Word# i))
    |
939 | int16BE (I16# i) = word16BE (W16# (int2Word# i))
    |                                    ^^^^^^^^^^^

copying path '/nix/store/sdyrgqlqyvmixdxjqi6sa9zsl68vmsdv-tree-diff-lib-tree-diff-0.2.1.1' from 's3://circuithub-nix-binary-cache'...
src/Data/Bytes/Builder/Bounded.hs:939:46: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int16#’
    • In the first argument of ‘int2Word#’, namely ‘i’
      In the first argument of ‘W16#’, namely ‘(int2Word# i)’
      In the first argument of ‘word16BE’, namely ‘(W16# (int2Word# i))’
    |
939 | int16BE (I16# i) = word16BE (W16# (int2Word# i))
    |                                              ^

src/Data/Bytes/Builder/Bounded.hs:945:36: error:
    • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
    • In the first argument of ‘W32#’, namely ‘(int2Word# i)’
      In the first argument of ‘word32LE’, namely ‘(W32# (int2Word# i))’
      In the expression: word32LE (W32# (int2Word# i))
    |
945 | int32LE (I32# i) = word32LE (W32# (int2Word# i))
    |                                    ^^^^^^^^^^^

src/Data/Bytes/Builder/Bounded.hs:945:46: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int32#’
    • In the first argument of ‘int2Word#’, namely ‘i’
      In the first argument of ‘W32#’, namely ‘(int2Word# i)’
      In the first argument of ‘word32LE’, namely ‘(W32# (int2Word# i))’
    |
945 | int32LE (I32# i) = word32LE (W32# (int2Word# i))
    |                                              ^

src/Data/Bytes/Builder/Bounded.hs:948:36: error:
    • Couldn't match expected type ‘Word16#’ with actual type ‘Word#’
    • In the first argument of ‘W16#’, namely ‘(int2Word# i)’
      In the first argument of ‘word16LE’, namely ‘(W16# (int2Word# i))’
      In the expression: word16LE (W16# (int2Word# i))
    |
948 | int16LE (I16# i) = word16LE (W16# (int2Word# i))
    |                                    ^^^^^^^^^^^

src/Data/Bytes/Builder/Bounded.hs:948:46: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int16#’
    • In the first argument of ‘int2Word#’, namely ‘i’
      In the first argument of ‘W16#’, namely ‘(int2Word# i)’
      In the first argument of ‘word16LE’, namely ‘(W16# (int2Word# i))’
    |
948 | int16LE (I16# i) = word16LE (W16# (int2Word# i))
    |                                              ^

src/Data/Bytes/Builder/Bounded.hs:1075:32: error:
    • Couldn't match expected type ‘Word8#’ with actual type ‘Word#’
    • In the first argument of ‘W8#’, namely ‘w’
      In the expression: W8# w
      In an equation for ‘unsafeWordToWord8’:
          unsafeWordToWord8 (W# w) = W8# w
     |
1075 | unsafeWordToWord8 (W# w) = W8# w
     |                                ^
```

### PR DESCRIPTION
**Pull request by ocharles**
Fixes #25

### CODE REVIEW

**Comment by andrewthad** [comment]
This looks good. Did you build and run the test suite on GHC 8.10.7, 9.0.2, and 9.2.1? If not, I can do so.

**Comment by ocharles** [comment]
9.2 yes, others I don't think so. I had some build environment problems but that should be all fixed now. I'll try all those compilers tomorrow

**Comment by ocharles** [comment]
@teto Huh, you're right though - this PR does specify `base < 4.16`. Yet for some reason it still configures?

**Comment by andrewthad** [comment]
On https://github.com/byteverse/bytebuild/pull/27, I've added some small improvements (like bumping the upper bound on base). @ocharles Can you confirm there that there's nothing else to be done, and I'll squash and merge it.

I'm not sure how you had been able to build with 9.2. Maybe you had a cabal.project.local file with allow-newer set.
